name: zedNpc
version: '${version}'
main: me.lidan.zednpc.ZedNpc
api-version: '1.13'
authors: [ LidanTheDev ]
description: ZNPCs command wrapper for easier use
depend:
  - ServersNPC
softdepend:
  - PlaceholderAPI