name: Java CI with Gradle

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'gradle'

    - name: Cache ZNPCs jar
      uses: actions/cache@v4
      id: znpcs-cache
      with:
        path: libs
        key: znpcs-jar-v1.4

    - name: Download ZNPCs jar if not cached
      if: steps.znpcs-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p libs
        curl -L --retry 3 --fail -o libs/znpcs-5.0.jar https://github.com/lidanthedev/ZedNpc/releases/download/v0.2.0-alpha/znpcs-5.0.jar
        file libs/znpcs-5.0.jar
        echo "Verifying checksum..."
        echo "C916714BCCF8AD42ACDA8529CFEF0B28714E880089D10C6CA9A3B20E0F4FAD86  libs/znpcs-5.0.jar" > znpcs.sha256
        sha256sum -c znpcs.sha256

    - name: Set execute permissions
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build --no-daemon
