name: Java CI with Gradle

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'gradle'

    - name: Cache ZNPCs jar
      uses: actions/cache@v3
      id: znpcs-cache
      with:
        path: libs
        key: znpcs-jar-v1.1

    - name: Download ZNPCs jar if not cached
      if: steps.znpcs-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p libs
        curl -L -o libs/znpcs-5.0.jar https://github.com/lidanthedev/ZedNpc/releases/download/untagged-2d31be395ba356bd89d0/znpcs-5.0.jar

    - name: Set execute permissions
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build --no-daemon
